In [1]:
!pip install sentence-transformers pandas numpy scikit-learn

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.9.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.17.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [3]:
with open("candidates.jsonl", "r", encoding="utf-8") as f:
    for i in range(5):
        print(f.readline())
        print("-"*100)

{"candidate_id": "CAND_0000001", "profile": {"anonymized_name": "Ira Vora", "headline": "Backend Engineer | SQL, Spark, Cloud", "summary": "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid \u2014 Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side \u2014 Python, SQL, Spark, Airflow, warehouse design \u2014 and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.", "location": "Toronto", "country": "Canada", "years_of_experience": 6.9, "current_title": "Backend Engineer", "current_company": "Mindtree", "current_company_size": "10001+", "current_industry": "IT Services"}, "career_history": [{"company": "Mindtree", "title": "Backend Engineer", "start_date": "2024-03-08", "end_date": null, "duration_months": 27, "is_current": true, "industry": "IT Services", "company_size": "10001+", "description": "Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure."}, {"company": "Dunder Mifflin", "title": "Analytics Engineer", "start_date": "2019-07-03", "end_date": "2024-01-08", "duration_months": 55, "is_current": false, "industry": "Paper Products", "company_size": "201-500", "description": "Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues \u2014 wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models."}], "education": [{"institution": "Lovely Professional University", "degree": "B.E.", "field_of_study": "Computer Science", "start_year": 2017, "end_year": 2020, "grade": "8.24 CGPA", "tier": "tier_3"}], "skills": [{"name": "Tailwind", "proficiency": "intermediate", "endorsements": 3, "duration_months": 13}, {"name": "NLP", "proficiency": "advanced", "endorsements": 37, "duration_months": 26}, {"name": "Image Classification", "proficiency": "advanced", "endorsements": 7, "duration_months": 40}, {"name": "Fine-tuning LLMs", "proficiency": "advanced", "endorsements": 21, "duration_months": 36}, {"name": "Weights & Biases", "proficiency": "intermediate", "endorsements": 13, "duration_months": 30}, {"name": "Speech Recognition", "proficiency": "advanced", "endorsements": 52, "duration_months": 33}, {"name": "Photoshop", "proficiency": "intermediate", "endorsements": 8, "duration_months": 24}, {"name": "TTS", "proficiency": "advanced", "endorsements": 56, "duration_months": 60}, {"name": "LoRA", "proficiency": "intermediate", "endorsements": 0, "duration_months": 28}, {"name": "Apache Beam", "proficiency": "intermediate", "endorsements": 4, "duration_months": 9}, {"name": "AWS", "proficiency": "beginner", "endorsements": 5, "duration_months": 8}, {"name": "Flask", "proficiency": "beginner", "endorsements": 15, "duration_months": 15}, {"name": "BentoML", "proficiency": "intermediate", "endorsements": 3, "duration_months": 36}, {"name": "Milvus", "proficiency": "advanced", "endorsements": 40, "duration_months": 35}, {"name": "GANs", "proficiency": "advanced", "endorsements": 12, "duration_months": 19}, {"name": "Statistical Modeling", "proficiency": "intermediate", "endorsements": 9, "duration_months": 8}, {"name": "GCP", "proficiency": "beginner", "endorsements": 7, "duration_months": 2}], "certifications": [], "languages": [{"language": "English", "proficiency": "professional"}, {"language": "Hindi", "proficiency": "conversational"}], "redrob_signals": {"profile_completeness_score": 86.9, "signup_date": "2025-10-16", "last_active_date": "2026-05-20", "open_to_work_flag": true, "profile_views_received_30d": 23, "applications_submitted_30d": 2, "recruiter_response_rate": 0.34, "avg_response_time_hours": 177.8, "skill_assessment_scores": {"NLP": 38.8, "Image Classification": 64.8, "Fine-tuning LLMs": 41.6, "Speech Recognition": 53.7}, "connection_count": 356, "endorsements_received": 35, "notice_period_days": 60, "expected_salary_range_inr_lpa": {"min": 18.7, "max": 36.1}, "preferred_work_mode": "onsite", "willing_to_relocate": false, "github_activity_score": 9.2, "search_appearance_30d": 249, "saved_by_recruiters_30d": 4, "interview_completion_rate": 0.71, "offer_acceptance_rate": 0.58, "verified_email": true, "verified_phone": true, "linkedin_connected": false}}

----------------------------------------------------------------------------------------------------
{"candidate_id": "CAND_0000002", "profile": {"anonymized_name": "Saanvi Sethi", "headline": "Operations Manager | 12.5+ yrs experience", "summary": "Professional with 12.5+ years of experience. My professional background is in marketing manager \u2014 I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", "location": "Chennai, Tamil Nadu", "country": "India", "years_of_experience": 12.5, "current_title": "Operations Manager", "current_company": "Wipro", "current_company_size": "10001+", "current_industry": "IT Services"}, "career_history": [{"company": "Wipro", "title": "Operations Manager", "start_date": "2022-11-14", "end_date": null, "duration_months": 43, "is_current": true, "industry": "IT Services", "company_size": "10001+", "description": "Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise."}, {"company": "Wipro", "title": "Operations Manager", "start_date": "2021-09-13", "end_date": "2022-11-07", "duration_months": 14, "is_current": false, "industry": "IT Services", "company_size": "10001+", "description": "Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up."}, {"company": "Acme Corp", "title": "Marketing Manager", "start_date": "2017-03-08", "end_date": "2021-08-14", "duration_months": 54, "is_current": false, "industry": "Manufacturing", "company_size": "201-500", "description": "Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics \u2014 including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality."}, {"company": "Dunder Mifflin", "title": "Marketing Manager", "start_date": "2014-01-23", "end_date": "2017-03-08", "duration_months": 38, "is_current": false, "industry": "Paper Products", "company_size": "201-500", "description": "Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite, Figma, and the production side of brand and packaging design."}], "education": [{"institution": "Local Engineering College", "degree": "B.Sc", "field_of_study": "Mathematics", "start_year": 2007, "end_year": 2011, "grade": "77%", "tier": "tier_4"}], "skills": [{"name": "Project Management", "proficiency": "intermediate", "endorsements": 14, "duration_months": 23}, {"name": "React", "proficiency": "intermediate", "endorsements": 6, "duration_months": 35}, {"name": "Photoshop", "proficiency": "intermediate", "endorsements": 9, "duration_months": 35}, {"name": "TypeScript", "proficiency": "beginner", "endorsements": 2, "duration_months": 3}, {"name": "Marketing", "proficiency": "beginner", "endorsements": 9, "duration_months": 11}, {"name": "Kafka", "proficiency": "intermediate", "endorsements": 3, "duration_months": 16}, {"name": "JavaScript", "proficiency": "beginner", "endorsements": 9, "duration_months": 3}, {"name": "Feature Engineering", "proficiency": "intermediate", "endorsements": 11, "duration_months": 27}, {"name": "GCP", "proficiency": "intermediate", "endorsements": 7, "duration_months": 30}], "certifications": [], "languages": [{"language": "English", "proficiency": "professional"}, {"language": "Hindi", "proficiency": "conversational"}], "redrob_signals": {"profile_completeness_score": 78.7, "signup_date": "2025-07-28", "last_active_date": "2025-11-12", "open_to_work_flag": true, "profile_views_received_30d": 7, "applications_submitted_30d": 1, "recruiter_response_rate": 0.29, "avg_response_time_hours": 171.6, "skill_assessment_scores": {}, "connection_count": 179, "endorsements_received": 3, "notice_period_days": 60, "expected_salary_range_inr_lpa": {"min": 8.8, "max": 9.0}, "preferred_work_mode": "flexible", "willing_to_relocate": false, "github_activity_score": -1, "search_appearance_30d": 107, "saved_by_recruiters_30d": 10, "interview_completion_rate": 0.62, "offer_acceptance_rate": -1, "verified_email": false, "verified_phone": false, "linkedin_connected": false}}

----------------------------------------------------------------------------------------------------
{"candidate_id": "CAND_0000003", "profile": {"anonymized_name": "Yash Agarwal", "headline": "Customer Support | 1.1+ yrs experience", "summary": "Professional with 1.1+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", "location": "Austin", "country": "USA", "years_of_experience": 1.1, "current_title": "Customer Support", "current_company": "TCS", "current_company_size": "10001+", "current_industry": "IT Services"}, "career_history": [{"company": "TCS", "title": "Customer Support", "start_date": "2025-05-02", "end_date": null, "duration_months": 13, "is_current": true, "industry": "IT Services", "company_size": "10001+", "description": "Business analyst at a consulting firm, working primarily with retail and CPG clients. Conducted business diagnostics, process re-engineering work, and digital transformation strategy projects. Strong on stakeholder management, structured problem-solving, and the typical consulting toolkit (slide-craft, Excel modeling, executive communication). Recent project work involved AI-strategy advisory but my own technical depth in AI is limited."}], "education": [{"institution": "Local Engineering College", "degree": "M.E.", "field_of_study": "Chemical Engineering", "start_year": 2005, "end_year": 2010, "grade": "6.82 CGPA", "tier": "tier_4"}, {"institution": "Chandigarh University", "degree": "M.Sc", "field_of_study": "Information Technology", "start_year": 2017, "end_year": 2021, "grade": "87%", "tier": "tier_3"}], "skills": [{"name": "Angular", "proficiency": "intermediate", "endorsements": 13, "duration_months": 10}, {"name": "SEO", "proficiency": "beginner", "endorsements": 11, "duration_months": 11}, {"name": "Excel", "proficiency": "intermediate", "endorsements": 2, "duration_months": 15}, {"name": "Accounting", "proficiency": "beginner", "endorsements": 7, "duration_months": 18}, {"name": "Kubernetes", "proficiency": "intermediate", "endorsements": 0, "duration_months": 34}, {"name": "Databricks", "proficiency": "beginner", "endorsements": 14, "duration_months": 18}], "certifications": [], "languages": [{"language": "English", "proficiency": "professional"}, {"language": "Hindi", "proficiency": "professional"}], "redrob_signals": {"profile_completeness_score": 31.9, "signup_date": "2024-08-02", "last_active_date": "2026-03-21", "open_to_work_flag": false, "profile_views_received_30d": 1, "applications_submitted_30d": 9, "recruiter_response_rate": 0.46, "avg_response_time_hours": 119.4, "skill_assessment_scores": {}, "connection_count": 19, "endorsements_received": 46, "notice_period_days": 150, "expected_salary_range_inr_lpa": {"min": 11.2, "max": 18.1}, "preferred_work_mode": "hybrid", "willing_to_relocate": false, "github_activity_score": -1, "search_appearance_30d": 28, "saved_by_recruiters_30d": 4, "interview_completion_rate": 0.86, "offer_acceptance_rate": -1, "verified_email": true, "verified_phone": false, "linkedin_connected": false}}

----------------------------------------------------------------------------------------------------
{"candidate_id": "CAND_0000004", "profile": {"anonymized_name": "Anil Bose", "headline": "Marketing Manager | Driving business outcomes", "summary": "Professional with 3.8+ years of experience. My professional background is in marketing manager \u2014 I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", "location": "Sydney", "country": "Australia", "years_of_experience": 3.8, "current_title": "Marketing Manager", "current_company": "Dunder Mifflin", "current_company_size": "201-500", "current_industry": "Paper Products"}, "career_history": [{"company": "Dunder Mifflin", "title": "Marketing Manager", "start_date": "2025-04-02", "end_date": null, "duration_months": 14, "is_current": true, "industry": "Paper Products", "company_size": "201-500", "description": "Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up."}, {"company": "Infosys", "title": "Operations Manager", "start_date": "2023-07-28", "end_date": "2025-03-19", "duration_months": 20, "is_current": false, "industry": "IT Services", "company_size": "10001+", "description": "Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics \u2014 including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality."}, {"company": "Globex Inc", "title": "Business Analyst", "start_date": "2022-08-02", "end_date": "2023-05-29", "duration_months": 10, "is_current": false, "industry": "Manufacturing", "company_size": "501-1000", "description": "Operations management role at a logistics company. Owned daily fulfillment operations across 3 warehouses, managing a team of 80 across receiving, picking, packing, and outbound. Built and tracked the operational KPIs (on-time fulfillment, accuracy, cost per order) and led the continuous improvement initiatives that drove a 22% productivity gain over 18 months."}], "education": [{"institution": "Local Engineering College", "degree": "B.Tech", "field_of_study": "Machine Learning", "start_year": 2015, "end_year": 2019, "grade": "7.72 CGPA", "tier": "tier_4"}, {"institution": "Lovely Professional University", "degree": "Ph.D", "field_of_study": "Electronics", "start_year": 2013, "end_year": 2016, "grade": "7.61 CGPA", "tier": "tier_3"}], "skills": [{"name": "Node.js", "proficiency": "intermediate", "endorsements": 1, "duration_months": 20}, {"name": "Content Writing", "proficiency": "beginner", "endorsements": 7, "duration_months": 3}, {"name": "Redux", "proficiency": "beginner", "endorsements": 14, "duration_months": 8}, {"name": "Airflow", "proficiency": "intermediate", "endorsements": 11, "duration_months": 27}, {"name": "GraphQL", "proficiency": "beginner", "endorsements": 13, "duration_months": 2}, {"name": "Object Detection", "proficiency": "intermediate", "endorsements": 3, "duration_months": 17}, {"name": "Webpack", "proficiency": "beginner", "endorsements": 10, "duration_months": 7}, {"name": "Six Sigma", "proficiency": "beginner", "endorsements": 1, "duration_months": 12}, {"name": "SAP", "proficiency": "intermediate", "endorsements": 6, "duration_months": 9}, {"name": "JavaScript", "proficiency": "intermediate", "endorsements": 14, "duration_months": 29}], "certifications": [{"name": "AWS Certified Cloud Practitioner", "issuer": "AWS", "year": 2025}, {"name": "Scrum Master Certified", "issuer": "Scrum Alliance", "year": 2025}], "languages": [{"language": "English", "proficiency": "professional"}, {"language": "Hindi", "proficiency": "professional"}], "redrob_signals": {"profile_completeness_score": 28.5, "signup_date": "2025-07-21", "last_active_date": "2026-03-25", "open_to_work_flag": false, "profile_views_received_30d": 3, "applications_submitted_30d": 9, "recruiter_response_rate": 0.26, "avg_response_time_hours": 104.1, "skill_assessment_scores": {}, "connection_count": 485, "endorsements_received": 22, "notice_period_days": 120, "expected_salary_range_inr_lpa": {"min": 4.6, "max": 6.7}, "preferred_work_mode": "onsite", "willing_to_relocate": true, "github_activity_score": -1, "search_appearance_30d": 5, "saved_by_recruiters_30d": 8, "interview_completion_rate": 0.35, "offer_acceptance_rate": -1, "verified_email": true, "verified_phone": true, "linkedin_connected": true}}

----------------------------------------------------------------------------------------------------

In [4]:
import os

print(os.path.getsize("candidates.jsonl"))

137363456

In [5]:
with open("candidates.jsonl", "r", encoding="utf-8") as f:
    for i in range(10):
        line = f.readline()
        print(f"Line {i+1}:")
        print(line[:500])  # first 500 chars
        print("-"*80)

Line 1:
{"candidate_id": "CAND_0000001", "profile": {"anonymized_name": "Ira Vora", "headline": "Backend Engineer | SQL, Spark, Cloud", "summary": "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid \u2014 Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side \u2014 Python, SQL, Spark, Airflow, warehouse design \u20
--------------------------------------------------------------------------------
Line 2:
{"candidate_id": "CAND_0000002", "profile": {"anonymized_name": "Saanvi Sethi", "headline": "Operations Manager | 12.5+ yrs experience", "summary": "Professional with 12.5+ years of experience. My professional background is in marketing manager \u2014 I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation,
--------------------------------------------------------------------------------
Line 3:
{"candidate_id": "CAND_0000003", "profile": {"anonymized_name": "Yash Agarwal", "headline": "Customer Support | 1.1+ yrs experience", "summary": "Professional with 1.1+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation, and I th
--------------------------------------------------------------------------------
Line 4:
{"candidate_id": "CAND_0000004", "profile": {"anonymized_name": "Anil Bose", "headline": "Marketing Manager | Driving business outcomes", "summary": "Professional with 3.8+ years of experience. My professional background is in marketing manager \u2014 I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation,
--------------------------------------------------------------------------------
Line 5:
{"candidate_id": "CAND_0000005", "profile": {"anonymized_name": "Aisha Sethi", "headline": "Accountant | Helping teams scale", "summary": "Professional with 11.0+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think th
--------------------------------------------------------------------------------
Line 6:
{"candidate_id": "CAND_0000006", "profile": {"anonymized_name": "Rajesh Desai", "headline": "Business Analyst | 6.0+ yrs experience", "summary": "Professional with 6.0+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation, and I th
--------------------------------------------------------------------------------
Line 7:
{"candidate_id": "CAND_0000007", "profile": {"anonymized_name": "Vihaan Bose", "headline": "Civil Engineer | 5.5+ yrs experience", "summary": "Professional with 5.5+ years of experience. My professional background is in marketing manager \u2014 I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation, and I t
--------------------------------------------------------------------------------
Line 8:
{"candidate_id": "CAND_0000008", "profile": {"anonymized_name": "Shaurya Chatterjee", "headline": "Operations Manager | 3.6+ yrs experience", "summary": "Professional with 3.6+ years of experience. I've spent my career in marketing manager roles, mostly focused on driving outcomes through process, people, and customer relationships. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation,
--------------------------------------------------------------------------------
Line 9:
{"candidate_id": "CAND_0000009", "profile": {"anonymized_name": "Amit Shah", "headline": "Mechanical Engineer | Driving business outcomes", "summary": "Professional with 11.0+ years of experience. My professional background is in marketing manager \u2014 I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creatio
--------------------------------------------------------------------------------
Line 10:
{"candidate_id": "CAND_0000010", "profile": {"anonymized_name": "Aarav Kapoor", "headline": "Data Engineer | Data pipelines & analytics", "summary": "Software / data professional with 4.6 years of experience building data pipelines, backend systems, and analytics infrastructure. Most of my work has been data pipelines and analytics infrastructure; I've shipped a couple of small ML features but it's not the core of my day. My toolkit is solid on the data engineering side \u2014 Python, SQL, Spark
--------------------------------------------------------------------------------

In [6]:
import os

print("Size (MB):", os.path.getsize("candidates.jsonl") / (1024*1024))

Size (MB): 288.0

In [7]:
import json

with open("candidates.jsonl", "r", encoding="utf-8") as f:
    try:
        data = json.load(f)
        print("Loaded as JSON array")
        print(type(data))
        print(len(data))
    except Exception as e:
        print("Error:", e)

Error: Extra data: line 2 column 1 (char 5198)

In [8]:
import json

with open("candidates.jsonl", "r", encoding="utf-8") as f:
    for i, line in enumerate(f, start=1):
        try:
            json.loads(line)
        except Exception as e:
            print("Error at line:", i)
            print("Error:", e)
            print("First 500 chars:")
            print(line[:500])
            break

Error at line: 74225
Error: Unterminated string starting at: line 1 column 4778 (char 4777)
First 500 chars:
{"candidate_id": "CAND_0074225", "profile": {"anonymized_name": "Kabir Agarwal", "headline": "Machine Learning Engineer | ML, NLP, Recommendation Systems", "summary": "Machine learning engineer with 4.3 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, my main project for the last 18 months has been the recommendation system that p

In [9]:
with open("candidates.jsonl", "r", encoding="utf-8") as f:
    text = f.read(10000)

print(text)

{"candidate_id": "CAND_0000001", "profile": {"anonymized_name": "Ira Vora", "headline": "Backend Engineer | SQL, Spark, Cloud", "summary": "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid \u2014 Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side \u2014 Python, SQL, Spark, Airflow, warehouse design \u2014 and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.", "location": "Toronto", "country": "Canada", "years_of_experience": 6.9, "current_title": "Backend Engineer", "current_company": "Mindtree", "current_company_size": "10001+", "current_industry": "IT Services"}, "career_history": [{"company": "Mindtree", "title": "Backend Engineer", "start_date": "2024-03-08", "end_date": null, "duration_months": 27, "is_current": true, "industry": "IT Services", "company_size": "10001+", "description": "Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure."}, {"company": "Dunder Mifflin", "title": "Analytics Engineer", "start_date": "2019-07-03", "end_date": "2024-01-08", "duration_months": 55, "is_current": false, "industry": "Paper Products", "company_size": "201-500", "description": "Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues \u2014 wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models."}], "education": [{"institution": "Lovely Professional University", "degree": "B.E.", "field_of_study": "Computer Science", "start_year": 2017, "end_year": 2020, "grade": "8.24 CGPA", "tier": "tier_3"}], "skills": [{"name": "Tailwind", "proficiency": "intermediate", "endorsements": 3, "duration_months": 13}, {"name": "NLP", "proficiency": "advanced", "endorsements": 37, "duration_months": 26}, {"name": "Image Classification", "proficiency": "advanced", "endorsements": 7, "duration_months": 40}, {"name": "Fine-tuning LLMs", "proficiency": "advanced", "endorsements": 21, "duration_months": 36}, {"name": "Weights & Biases", "proficiency": "intermediate", "endorsements": 13, "duration_months": 30}, {"name": "Speech Recognition", "proficiency": "advanced", "endorsements": 52, "duration_months": 33}, {"name": "Photoshop", "proficiency": "intermediate", "endorsements": 8, "duration_months": 24}, {"name": "TTS", "proficiency": "advanced", "endorsements": 56, "duration_months": 60}, {"name": "LoRA", "proficiency": "intermediate", "endorsements": 0, "duration_months": 28}, {"name": "Apache Beam", "proficiency": "intermediate", "endorsements": 4, "duration_months": 9}, {"name": "AWS", "proficiency": "beginner", "endorsements": 5, "duration_months": 8}, {"name": "Flask", "proficiency": "beginner", "endorsements": 15, "duration_months": 15}, {"name": "BentoML", "proficiency": "intermediate", "endorsements": 3, "duration_months": 36}, {"name": "Milvus", "proficiency": "advanced", "endorsements": 40, "duration_months": 35}, {"name": "GANs", "proficiency": "advanced", "endorsements": 12, "duration_months": 19}, {"name": "Statistical Modeling", "proficiency": "intermediate", "endorsements": 9, "duration_months": 8}, {"name": "GCP", "proficiency": "beginner", "endorsements": 7, "duration_months": 2}], "certifications": [], "languages": [{"language": "English", "proficiency": "professional"}, {"language": "Hindi", "proficiency": "conversational"}], "redrob_signals": {"profile_completeness_score": 86.9, "signup_date": "2025-10-16", "last_active_date": "2026-05-20", "open_to_work_flag": true, "profile_views_received_30d": 23, "applications_submitted_30d": 2, "recruiter_response_rate": 0.34, "avg_response_time_hours": 177.8, "skill_assessment_scores": {"NLP": 38.8, "Image Classification": 64.8, "Fine-tuning LLMs": 41.6, "Speech Recognition": 53.7}, "connection_count": 356, "endorsements_received": 35, "notice_period_days": 60, "expected_salary_range_inr_lpa": {"min": 18.7, "max": 36.1}, "preferred_work_mode": "onsite", "willing_to_relocate": false, "github_activity_score": 9.2, "search_appearance_30d": 249, "saved_by_recruiters_30d": 4, "interview_completion_rate": 0.71, "offer_acceptance_rate": 0.58, "verified_email": true, "verified_phone": true, "linkedin_connected": false}}
{"candidate_id": "CAND_0000002", "profile": {"anonymized_name": "Saanvi Sethi", "headline": "Operations Manager | 12.5+ yrs experience", "summary": "Professional with 12.5+ years of experience. My professional background is in marketing manager \u2014 I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work \u2014 I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities.", "location": "Chennai, Tamil Nadu", "country": "India", "years_of_experience": 12.5, "current_title": "Operations Manager", "current_company": "Wipro", "current_company_size": "10001+", "current_industry": "IT Services"}, "career_history": [{"company": "Wipro", "title": "Operations Manager", "start_date": "2022-11-14", "end_date": null, "duration_months": 43, "is_current": true, "industry": "IT Services", "company_size": "10001+", "description": "Customer support team lead at a SaaS product. Managed a team of 8 support agents handling tier-1 and tier-2 tickets; owned the escalation process to engineering and the customer-feedback loop to product. Built out the support knowledge base and the agent training program. Strong on the people-management side and the process side; lighter on technical depth beyond product expertise."}, {"company": "Wipro", "title": "Operations Manager", "start_date": "2021-09-13", "end_date": "2022-11-07", "duration_months": 14, "is_current": false, "industry": "IT Services", "company_size": "10001+", "description": "Mechanical engineering design role at a hardware-product company. Led the design of two product subsystems through full lifecycle: concept, DFM/DFMA review, prototype, production tooling. Comfortable with CAD (SolidWorks, Creo), FEA (ANSYS), and the typical hardware-development cadence. Worked closely with manufacturing partners on production scale-up."}, {"company": "Acme Corp", "title": "Marketing Manager", "start_date": "2017-03-08", "end_date": "2021-08-14", "duration_months": 54, "is_current": false, "industry": "Manufacturing", "company_size": "201-500", "description": "Content writing and SEO strategy for a tech-focused publication. Wrote longform articles on developer tools, cloud platforms, and AI/ML topics \u2014 including some that ranked on the first page of search for high-competition keywords. Managed a freelance writer pool and the editorial calendar. Recent work has been on AI-assisted content production, using LLM tools for research, drafting, and editing while maintaining editorial quality."}, {"company": "Dunder Mifflin", "title": "Marketing Manager", "start_date": "2014-01-23", "end_date": "2017-03-08", "duration_months": 38, "is_current": false, "industry": "Paper Products", "company_size": "201-500", "description": "Brand design and creative direction at a consumer-products company. Owned brand identity (logo, visual system, typography), packaging design, and digital creative across web and social. Led the recent rebrand and managed a small external agency for production work. Comfortable across the Adobe suite, Figma, and the production side of brand and packaging design."}], "education": [{"institution": "Local Engineering College", "degree": "B.Sc", "field_of_study": "Mathematics", "start_year": 2007, "end_year": 2011, "grade": "77%", "tier": "tier_4"}], "skills": [{"name": "Project Management", "proficiency": "intermediate", "endorsements": 14, "duration_months": 23}, {"name": "React", "proficiency": "intermediate", "endorsements": 6, "duration_months": 35}, {"name": "Photoshop", "proficiency": "intermediate", "endorsements": 9, "duration_months": 35}, {"name": "TypeScript", "proficiency": "beginner", "endorsements": 2, "duration_months": 3}, {"name": "Marketing", "proficiency": "beginner", "endorsements": 9, "duration_months": 11}, {"name": "Kafka", "proficiency": "intermediate", "endorsements": 3, "duration_months": 16}, {"name": "JavaScript", "proficiency": "beginner", "endorsements": 9, "duration_months": 3}, {"name": "Feature Engineering", "proficiency": "intermediate", "endorsements": 11, "duration_months": 27}, {"name": "GCP", "proficiency": "intermediate", "endorsements": 7, "duration_months": 30}], "certifications": [], "languages": [{"language": "English", "proficiency": "professional"}, {"language": "Hindi", "proficiency": "conversational"}], "redrob_signals": {"profile_completeness_score": 78.7, "signup_date": "2025-07-28", "last_active_date": "2025-11-12", "open_to_work_flag": true, "profile_views_received_30d": 7, "applications_submitted_30d": 1, "recruiter_response_rate": 0.29, "avg_response_time_hours": 171.6, "skill_asses

In [10]:
import json

candidates = []
bad_lines = []

with open("candidates.jsonl", "r", encoding="utf-8") as f:
    for i, line in enumerate(f, start=1):
        try:
            candidates.append(json.loads(line))
        except Exception:
            bad_lines.append(i)

print("Loaded:", len(candidates))
print("Bad lines:", len(bad_lines))
print("Examples:", bad_lines[:10])

Loaded: 100000
Bad lines: 0
Examples: []

In [11]:
import pandas as pd

records = []

with open("candidates.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        try:
            records.append(json.loads(line))
        except:
            pass

df = pd.DataFrame(records)

print(df.shape)

(100000, 8)

In [12]:
print(candidates[0].keys())

dict_keys(['candidate_id', 'profile', 'career_history', 'education', 'skills', 'certifications', 'languages', 'redrob_signals'])

In [13]:
print(candidates[0]["candidate_id"])
print(candidates[0]["profile"])

CAND_0000001
{'anonymized_name': 'Ira Vora', 'headline': 'Backend Engineer | SQL, Spark, Cloud', 'summary': "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.", 'location': 'Toronto', 'country': 'Canada', 'years_of_experience': 6.9, 'current_title': 'Backend Engineer', 'current_company': 'Mindtree', 'current_company_size': '10001+', 'current_industry': 'IT Services'}

In [14]:
import os

for f in os.listdir():
    print(f)

.config
candidates.jsonl
[PUB] India_runs_data_and_ai_challenge.zip
job_description.docx
sample_data

In [15]:
with open("YOUR_JD_FILE_NAME", "r", encoding="utf-8") as f:
    jd_text = f.read()

print(jd_text[:1000])

FileNotFoundError: [Errno 2] No such file or directory: 'YOUR_JD_FILE_NAME'

In [16]:
import os

for f in os.listdir():
    print(f)

.config
candidates.jsonl
[PUB] India_runs_data_and_ai_challenge.zip
job_description.docx
sample_data

In [17]:
with open("job_description.txt", "r", encoding="utf-8") as f:
    jd_text = f.read()

print(jd_text[:1000])

FileNotFoundError: [Errno 2] No such file or directory: 'job_description.txt'

In [18]:
import os

files = os.listdir()
print(files)

['.config', 'candidates.jsonl', '[PUB] India_runs_data_and_ai_challenge.zip', 'job_description.docx', 'sample_data']

In [19]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        print(os.path.join(root, file))

./candidates.jsonl
./[PUB] India_runs_data_and_ai_challenge.zip
./job_description.docx
./.config/gce
./.config/.last_update_check.json
./.config/default_configs.db
./.config/active_config
./.config/.last_opt_in_prompt.yaml
./.config/.last_survey_prompt.yaml
./.config/config_sentinel
./.config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
./.config/configurations/config_default
./.config/logs/2026.06.04/13.32.38.346437.log
./.config/logs/2026.06.04/13.32.02.654775.log
./.config/logs/2026.06.04/13.32.18.735754.log
./.config/logs/2026.06.04/13.32.39.344962.log
./.config/logs/2026.06.04/13.31.42.499627.log
./.config/logs/2026.06.04/13.32.21.210570.log
./sample_data/anscombe.json
./sample_data/README.md
./sample_data/mnist_train_small.csv
./sample_data/california_housing_test.csv
./sample_data/california_housing_train.csv
./sample_data/mnist_test.csv

In [20]:
!pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.1.1)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (4.15.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 8.5 MB/s eta 0:00:00
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0

In [21]:
from docx import Document

doc = Document("job_description.docx")

jd_text = "\n".join(
    para.text for para in doc.paragraphs
)

print(jd_text[:3000])

Job Description: Senior AI Engineer — Founding Team
Company: Redrob AI (Series A AI-native talent intelligence platform)
Location: Pune/Noida, India (Hybrid — flexible cadence) | Open to relocation candidates from Tier-1 Indian cities
Employment Type: Full-time
Experience Required: 5–9 years (see "what we mean by this" below)

Let's be honest about this role
We're going to write this JD differently from most. We're a Series A company that just raised our round and we're building a new AI Engineering org from scratch. This is the kind of role where the JD changes every six months because the company changes every six months. So instead of pretending we have a fixed checklist, we're going to tell you what we actually need and what we've gotten wrong before.
If you've spent your career at Google or Meta and you want a well-scoped role with a defined ladder, this isn't it.
If you've spent your career bouncing between early-stage startups and you want to "just code" without having to think about product or recruiter workflows or eval frameworks, this also isn't it.
We need someone who is simultaneously comfortable with two things that sound contradictory:
Deep technical depth in modern ML systems — embeddings, retrieval, ranking, LLMs, fine-tuning.
Scrappy product-engineering attitude — willing to ship a working ranker in a week even if the underlying ML is "obviously suboptimal," because we need to learn from real users before we know what to actually optimize for.
These are not contradictory in real life. They feel contradictory because of how engineering culture sorted itself into "researcher" vs "shipper" archetypes. We need both modes available in the same person, and we'd rather you tilt slightly toward shipper than toward researcher.

What you'd actually be doing
The high-level mandate: own the intelligence layer of Redrob's product. That means the ranking, retrieval, and matching systems that decide what recruiters see when they search for candidates and what candidates see when they search for roles.
In practical terms, your first 90 days will probably look like:
Weeks 1-3: Audit what we currently have (it's mostly BM25 + rule-based scoring, working but not great). Identify the 3-4 highest-leverage things to fix.
Weeks 4-8: Ship a v2 ranking system that demonstrably improves recruiter-engagement metrics. This will involve embeddings, hybrid retrieval, and probably some LLM-based re-ranking, but the architecture is your call.
Weeks 9-12: Set up the evaluation infrastructure — offline benchmarks, online A/B testing, recruiter-feedback loops — so we can keep improving without flying blind.
Beyond that, you'll be driving the long-term architecture of how we do candidate-JD matching at scale, mentoring the next round of hires (we're growing the team from 4 to 12 engineers in the next year), and working closely with our recruiter-experience PM on what to build.

What we mean by "5-9 years"
This is a range, not a requirement. Some people hit "senior

In [22]:
AI_SKILLS = {
    "LLM",
    "Fine-tuning LLMs",
    "RAG",
    "Embeddings",
    "NLP",
    "LoRA",
    "Milvus",
    "Vector DB",
    "Retrieval",
    "Ranking",
    "Recommendation Systems",
    "PyTorch",
    "TensorFlow",
    "Transformers",
    "LangChain",
    "LlamaIndex",
    "BentoML",
    "MLOps",
    "Feature Engineering"
}

In [23]:
def skill_score(c):

    skills = {
        s["name"]
        for s in c["skills"]
    }

    matches = len(
        skills.intersection(
            AI_SKILLS
        )
    )

    return min(matches / 10, 1.0)

In [24]:
def experience_score(c):

    exp = c["profile"].get(
        "years_of_experience",
        0
    )

    if 5 <= exp <= 9:
        return 1.0

    if 3 <= exp <= 12:
        return 0.7

    return 0.3

In [25]:
def behavior_score(c):

    s = c["redrob_signals"]

    score = 0

    score += (
        s.get(
            "recruiter_response_rate",
            0
        ) * 0.20
    )

    score += (
        s.get(
            "interview_completion_rate",
            0
        ) * 0.20
    )

    score += (
        s.get(
            "offer_acceptance_rate",
            0
        ) * 0.10
    )

    score += (
        min(
            s.get(
                "github_activity_score",
                0
            ) / 100,
            1
        ) * 0.20
    )

    score += (
        min(
            s.get(
                "profile_completeness_score",
                0
            ) / 100,
            1
        ) * 0.20
    )

    score += (
        0.10
        if s.get(
            "open_to_work_flag",
            False
        )
        else 0
    )

    return score

In [26]:
def location_score(c):

    profile = c["profile"]

    country = profile.get(
        "country",
        ""
    )

    if country == "India":
        return 1

    return 0.5

In [27]:
def final_score(c):

    return (

        0.40 * skill_score(c)

        + 0.25 * experience_score(c)

        + 0.25 * behavior_score(c)

        + 0.10 * location_score(c)

    )

In [28]:
scores = []

for c in candidates:

    scores.append({

        "candidate_id":
        c["candidate_id"],

        "score":
        final_score(c)

    })

In [29]:
import pandas as pd

ranked = pd.DataFrame(scores)

ranked = ranked.sort_values(
    "score",
    ascending=False
)

ranked["rank"] = range(
    1,
    len(ranked)+1
)

ranked.head(20)

       candidate_id    score  rank
86021  CAND_0086022  0.84740     1
11686  CAND_0011687  0.82360     2
45861  CAND_0045862  0.79745     3
37565  CAND_0037566  0.78075     4
29366  CAND_0029367  0.77950     5
77284  CAND_0077285  0.76490     6
37979  CAND_0037980  0.76180     7
18498  CAND_0018499  0.76065     8
60071  CAND_0060072  0.76010     9
2024   CAND_0002025  0.75635    10
41609  CAND_0041610  0.75400    11
88024  CAND_0088025  0.75195    12
77955  CAND_0077956  0.75085    13
70397  CAND_0070398  0.74945    14
49537  CAND_0049538  0.74610    15
74338  CAND_0074339  0.74545    16
86150  CAND_0086151  0.74420    17
1929   CAND_0001930  0.74380    18
73313  CAND_0073314  0.74185    19
33384  CAND_0033385  0.74015    20

In [30]:
ranked.to_csv(
    "submission.csv",
    index=False
)

In [31]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if "submission" in file.lower():
            print(file)

submission.csv

In [32]:
import pandas as pd

sub = pd.read_csv("submission.csv")

print(sub.head())
print(sub.columns.tolist())
print(sub.shape)

   candidate_id    score  rank
0  CAND_0086022  0.84740     1
1  CAND_0011687  0.82360     2
2  CAND_0045862  0.79745     3
3  CAND_0037566  0.78075     4
4  CAND_0029367  0.77950     5
['candidate_id', 'score', 'rank']
(100000, 3)

In [33]:
import zipfile

with zipfile.ZipFile("[PUB] India_runs_data_and_ai_challenge.zip", "r") as z:
    for f in z.namelist():
        print(f)

[PUB] India_runs_data_and_ai_challenge/
__MACOSX/._[PUB] India_runs_data_and_ai_challenge
[PUB] India_runs_data_and_ai_challenge/.DS_Store
__MACOSX/[PUB] India_runs_data_and_ai_challenge/._.DS_Store
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/
__MACOSX/[PUB] India_runs_data_and_ai_challenge/._India_runs_data_and_ai_challenge
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/job_description.docx
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._job_description.docx
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/redrob_signals_doc.docx
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._redrob_signals_doc.docx
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._validate_submission.py
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidate_schema.json
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._candidate_schema.json
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_metadata_template.yaml
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._submission_metadata_template.yaml
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_spec.docx
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._submission_spec.docx
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._candidates.jsonl
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_candidates.json
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._sample_candidates.json
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/README.docx
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._README.docx
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_submission.csv
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._sample_submission.csv

In [35]:
import zipfile

with zipfile.ZipFile("[PUB] India_runs_data_and_ai_challenge.zip", "r") as z:
    print("\n".join(z.namelist()))

[PUB] India_runs_data_and_ai_challenge/
__MACOSX/._[PUB] India_runs_data_and_ai_challenge
[PUB] India_runs_data_and_ai_challenge/.DS_Store
__MACOSX/[PUB] India_runs_data_and_ai_challenge/._.DS_Store
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/
__MACOSX/[PUB] India_runs_data_and_ai_challenge/._India_runs_data_and_ai_challenge
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/job_description.docx
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._job_description.docx
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/redrob_signals_doc.docx
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._redrob_signals_doc.docx
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._validate_submission.py
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidate_schema.json
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._candidate_schema.json
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_metadata_template.yaml
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._submission_metadata_template.yaml
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_spec.docx
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._submission_spec.docx
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._candidates.jsonl
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_candidates.json
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._sample_candidates.json
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/README.docx
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._README.docx
[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_submission.csv
__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._sample_submission.csv

In [36]:
import zipfile

with zipfile.ZipFile("[PUB] India_runs_data_and_ai_challenge.zip", "r") as z:
    z.extractall("challenge_files")

print("Extracted!")

Extracted!

In [37]:
import os

for root, dirs, files in os.walk("challenge_files"):
    for file in files:
        print(os.path.join(root, file))

challenge_files/__MACOSX/._[PUB] India_runs_data_and_ai_challenge
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/._.DS_Store
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/._India_runs_data_and_ai_challenge
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._submission_spec.docx
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._sample_submission.csv
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._job_description.docx
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._candidates.jsonl
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._sample_candidates.json
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._candidate_schema.json
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._redrob_signals_doc.docx
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._submission_metadata_template.yaml
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._validate_submission.py
challenge_files/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._README.docx
challenge_files/[PUB] India_runs_data_and_ai_challenge/.DS_Store
challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_spec.docx
challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_candidates.json
challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl
challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_metadata_template.yaml
challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py
challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/README.docx
challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/job_description.docx
challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/redrob_signals_doc.docx
challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_submission.csv
challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidate_schema.json

In [38]:
import pandas as pd

sample = pd.read_csv(
    "challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_submission.csv"
)

print(sample.head())
print(sample.columns.tolist())
print(sample.shape)

   candidate_id  rank  score  \
0  CAND_0004989     1  0.992
1  CAND_0001195     2  0.984
2  CAND_0003114     3  0.976
3  CAND_0000339     4  0.968
4  CAND_0001082     5  0.960

                                           reasoning
0  HR Manager with 6.1 yrs; 9 AI core skills; res...
1  HR Manager with 8.7 yrs; 9 AI core skills; res...
2  ML Engineer with 6.4 yrs; 4 AI core skills; re...
3  Content Writer with 8.3 yrs; 8 AI core skills;...
4  HR Manager with 5.0 yrs; 8 AI core skills; res...
['candidate_id', 'rank', 'score', 'reasoning']
(100, 4)

In [39]:
from docx import Document

doc = Document(
    "challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_spec.docx"
)

spec_text = "\n".join([p.text for p in doc.paragraphs])

print(spec_text[:5000])

Submission Specification — Redrob Hackathon v4
Read this carefully before submitting. Submissions that don't match this spec will be auto-rejected by the validator without scoring.

1. What you're submitting
A CSV file ranking the top 100 candidates from candidates.jsonl for the released job description.
Rank 1 is the best fit; rank 100 is the 100th best fit.
You do not rank candidates 101 onward — only the top 100.

2. File format
Filename
Your team's registered participant ID, with .csv extension. For example: team_xxx.csv.
Encoding
UTF-8.
Required columns (in this order)
candidate_id,rank,score,reasoning

Example
candidate_id,rank,score,reasoning
CAND_0042871,1,0.987,"Senior AI Engineer with 7 years building RAG systems at product companies; strong recent engagement and Bangalore-based."
CAND_0019884,2,0.973,"6 years applied ML; previously shipped vector search at scale; matches the 'product over research' profile in the JD."
CAND_0091235,3,0.962,"Strong NLP + retrieval background; some concern on notice period (120 days) but otherwise strong fit."
...
CAND_0007729,100,0.412,"Adjacent skills only — likely below cutoff but included as final filler given experience and engagement signals."

3. Rules
Format
Exactly 100 rows of data (plus 1 header row).
Each rank (1 through 100) appears exactly once.
Each candidate_id appears exactly once.
Every candidate_id must exist in the released candidates.jsonl.
score is non-increasing with rank — i.e., score at rank 1 ≥ score at rank 2 ≥ ... ≥ score at rank 100. Ties are allowed.
If two candidates have the same score, you must still assign unique ranks. Break score ties deterministically using a secondary signal from your model, or by candidate_id ascending.
Compute constraints
Your code that produces the submission must satisfy the following constraints:

Why these constraints? This is a real-world recruiting system, not a benchmark. A system that calls GPT-4 or Claude per candidate cannot scale to a 200K candidate pool in production. We want systems that have thought about latency-quality tradeoffs.
In practice, running an LLM call for each of 100,000 candidates will not fit the 5-minute CPU budget, even if the model runs locally. Plan for a small ranker over precomputed features, indexes, or compact local models.
You CANNOT, during the ranking step:
Call hosted LLM APIs.
Use GPUs.
Exceed the runtime/memory limits.
Enforcement. At Stage 3, top-N submissions must provide their full code repository. Your ranking step will be reproduced inside a sandboxed Docker container matching these constraints exactly. If your submission cannot be reproduced within these limits, it is disqualified at Stage 3, regardless of your composite score. Make sure your code runs locally on a 16 GB CPU-only machine within 5 minutes before you submit.
Three-submission cap
You may make at most 3 submissions total during the competition window. Your final entry is your last valid submission. Earlier submissions are not preserved.
We've kept this number low intentionally — without a live leaderboard, multiple submissions have limited value, and a low cap reduces gaming.
Reasoning column
The reasoning column is optional but heavily recommended. Top N submissions are advanced to Stage 4 (manual review) where reasoning quality is part of the evaluation.
At Stage 4, we sample 10 random rows from your submission and check each reasoning entry against the following:

What's penalized:
Empty reasoning
All-identical reasoning strings
Templated reasoning that just inserts the candidate's name
Reasoning that mentions skills not in the candidate's profile (hallucination)
Reasoning that contradicts the rank
Plain-language reasoning that demonstrates you actually understood the candidate's profile will rank highly here. Don't try to be impressive; try to be specific and honest.

4. How submissions are scored
Metrics
Your top-100 ranking is scored against the hidden ground truth using these metrics:

Final composite
Final composite = 0.50 × NDCG@10 + 0.30 × NDCG@50 + 0.15 × MAP + 0.05 × P@10
Scoring happens once, after submissions close. There is no public partition, no live leaderboard, and no per-submission feedback during the competition. Your score is computed against the full hidden ground truth and is revealed only when final results are announced.
Tiebreaks
If two submissions have identical composites:
Higher P@5 wins.
Higher P@10 wins.
Earlier submission timestamp wins.

5. Evaluation pipeline (stages)
Your submission flows through these stages:

Note on AI tool usage: You are allowed to use AI tools (Claude, GPT-4, etc.) as part of your development workflow. We expect many participants will. The evaluation is designed so that AI-assisted submissions where the human did real engineering work will succeed, while submissions that are mostly LLM output with minimal human engineering will fail at Stages 3-5. The compute constraint, code repo check, and defend-your-work interview together filter for genui

In [40]:
from docx import Document

doc = Document(
    "challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/README.docx"
)

readme_text = "\n".join([p.text for p in doc.paragraphs])

print(readme_text[:5000])

Redrob Hackathon — Participant Bundle
Welcome to the Intelligent Candidate Discovery & Ranking Challenge.

What's in this bundle

Getting started
1. Read the docs (~30 minutes)
In this order:
1.       job_description.md — understand what role you're ranking candidates for
2.       submission_spec.md — understand the rules and evaluation pipeline
3.       redrob_signals_doc.md — understand the trap candidates and signal envelopes
4.       candidate_schema.json — understand the candidate data structure
5.       Open sample_candidates.json and skim a few candidates to see what real data looks like
2. Unpack the candidate pool
gunzip -k candidates.jsonl.gz   # -k keeps the .gz; you get both files
 wc -l candidates.jsonl      	# should print 100000
Or load the gzipped file directly in Python:
import gzip, json
 with gzip.open("candidates.jsonl.gz", "rt") as f:
 	candidates = [json.loads(line) for line in f if line.strip()]
 print(len(candidates))  # 100000
3. Build your ranker
Your job: produce a CSV with the top 100 candidates for the JD, ranked best-fit first, with a 1-2 sentence reasoning for each.
The format is described in submission_spec.md Section 2-3. The compute constraints are in Section 3 (5 min, 16 GB, CPU only, no network during ranking).
4. Validate before submitting
This catches format errors before you upload. The validator handles both .jsonl and gzipped .jsonl.gz files.
5. Submit
Submit via the portal. You'll be asked for:
·         The CSV file
·         All the metadata from submission_metadata_template.yaml (team name, GitHub repo, sandbox link, AI tools declaration, etc.)
·         See submission_spec.md Section 10 for the full list
Sandbox link is required — a working hosted environment (HuggingFace Spaces, Streamlit Cloud, Replit, Colab, Docker, or Binder) where your ranker can be run on a small sample. See Section 10.5 for what counts as a valid sandbox.
Key things to know
·         No live leaderboard. Scores are revealed only after submissions close. There is no feedback during the competition.
·         Three submissions max. Your last valid submission counts.
·         AI tools are allowed. Declare them honestly. The evaluation is designed so that AI-assisted work where you did real engineering succeeds, while AI-only submissions fail at Stages 3-5.
·         The dataset contains traps. Keyword stuffers, plain-language Tier 5s, behavioral twins, and ~80 honeypots with subtly impossible profiles.Submissions with honeypot rate > 10% in top 100 are disqualified you. See redrob_signals_doc.md.
·         You will be interviewed if you reach the top X. Be prepared to walk through your architecture and defend your design choices.
Asking for help
If you find a bug in the bundle (e.g., schema doesn't match data, validator rejects valid format) please report it via the official hackathon support channel.
Good luck.

In [41]:
from docx import Document

doc = Document(
    "challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_spec.docx"
)

text = "\n".join(p.text for p in doc.paragraphs)

print(text)

Submission Specification — Redrob Hackathon v4
Read this carefully before submitting. Submissions that don't match this spec will be auto-rejected by the validator without scoring.

1. What you're submitting
A CSV file ranking the top 100 candidates from candidates.jsonl for the released job description.
Rank 1 is the best fit; rank 100 is the 100th best fit.
You do not rank candidates 101 onward — only the top 100.

2. File format
Filename
Your team's registered participant ID, with .csv extension. For example: team_xxx.csv.
Encoding
UTF-8.
Required columns (in this order)
candidate_id,rank,score,reasoning

Example
candidate_id,rank,score,reasoning
CAND_0042871,1,0.987,"Senior AI Engineer with 7 years building RAG systems at product companies; strong recent engagement and Bangalore-based."
CAND_0019884,2,0.973,"6 years applied ML; previously shipped vector search at scale; matches the 'product over research' profile in the JD."
CAND_0091235,3,0.962,"Strong NLP + retrieval background; some concern on notice period (120 days) but otherwise strong fit."
...
CAND_0007729,100,0.412,"Adjacent skills only — likely below cutoff but included as final filler given experience and engagement signals."

3. Rules
Format
Exactly 100 rows of data (plus 1 header row).
Each rank (1 through 100) appears exactly once.
Each candidate_id appears exactly once.
Every candidate_id must exist in the released candidates.jsonl.
score is non-increasing with rank — i.e., score at rank 1 ≥ score at rank 2 ≥ ... ≥ score at rank 100. Ties are allowed.
If two candidates have the same score, you must still assign unique ranks. Break score ties deterministically using a secondary signal from your model, or by candidate_id ascending.
Compute constraints
Your code that produces the submission must satisfy the following constraints:

Why these constraints? This is a real-world recruiting system, not a benchmark. A system that calls GPT-4 or Claude per candidate cannot scale to a 200K candidate pool in production. We want systems that have thought about latency-quality tradeoffs.
In practice, running an LLM call for each of 100,000 candidates will not fit the 5-minute CPU budget, even if the model runs locally. Plan for a small ranker over precomputed features, indexes, or compact local models.
You CANNOT, during the ranking step:
Call hosted LLM APIs.
Use GPUs.
Exceed the runtime/memory limits.
Enforcement. At Stage 3, top-N submissions must provide their full code repository. Your ranking step will be reproduced inside a sandboxed Docker container matching these constraints exactly. If your submission cannot be reproduced within these limits, it is disqualified at Stage 3, regardless of your composite score. Make sure your code runs locally on a 16 GB CPU-only machine within 5 minutes before you submit.
Three-submission cap
You may make at most 3 submissions total during the competition window. Your final entry is your last valid submission. Earlier submissions are not preserved.
We've kept this number low intentionally — without a live leaderboard, multiple submissions have limited value, and a low cap reduces gaming.
Reasoning column
The reasoning column is optional but heavily recommended. Top N submissions are advanced to Stage 4 (manual review) where reasoning quality is part of the evaluation.
At Stage 4, we sample 10 random rows from your submission and check each reasoning entry against the following:

What's penalized:
Empty reasoning
All-identical reasoning strings
Templated reasoning that just inserts the candidate's name
Reasoning that mentions skills not in the candidate's profile (hallucination)
Reasoning that contradicts the rank
Plain-language reasoning that demonstrates you actually understood the candidate's profile will rank highly here. Don't try to be impressive; try to be specific and honest.

4. How submissions are scored
Metrics
Your top-100 ranking is scored against the hidden ground truth using these metrics:

Final composite
Final composite = 0.50 × NDCG@10 + 0.30 × NDCG@50 + 0.15 × MAP + 0.05 × P@10
Scoring happens once, after submissions close. There is no public partition, no live leaderboard, and no per-submission feedback during the competition. Your score is computed against the full hidden ground truth and is revealed only when final results are announced.
Tiebreaks
If two submissions have identical composites:
Higher P@5 wins.
Higher P@10 wins.
Earlier submission timestamp wins.

5. Evaluation pipeline (stages)
Your submission flows through these stages:

Note on AI tool usage: You are allowed to use AI tools (Claude, GPT-4, etc.) as part of your development workflow. We expect many participants will. The evaluation is designed so that AI-assisted submissions where the human did real engineering work will succeed, while submissions that are mostly LLM output with minimal human engineering will fail at Stages 3-5. The compute constraint, code repo check, and defend-your-work interview together filter for genuine engineering, not for absence of AI use.

6. Common rejections (we see these every hackathon)
99 rows or 101 rows instead of exactly 100.
Ranks starting at 0 instead of 1.
Duplicate candidate_ids.
candidate_id typos that don't exist in candidates.jsonl.
All scores set to the same value (model isn't differentiating).
Scores increasing as rank increases (rank 1 has lowest score).
Submission file submitted as .xlsx or .json instead of .csv.
Double-check these locally before uploading — the server-side auto-validator rejects on any of them.

7. Honeypot warning
The dataset contains a small number (~80) of honeypot candidates with subtly impossible profiles (e.g., 8 years of experience at a company founded 3 years ago; "expert" proficiency in 10 skills with 0 years used). These are forced to relevance tier 0 in the ground truth.
If your submission ranks honeypots in the top 10, this is a strong signal that your system isn't reading profiles — it's just doing keyword embedding. We use the honeypot rate as a Stage 3 filter: submissions with honeypot rate > 10% in top 100 are disqualified.
You can identify honeypots through careful profile inspection. We expect a good ranking system to naturally avoid them; you don't need to special-case them.

8. Leaderboard policy
The leaderboard is hidden during the competition. You will not see your score until final results are announced. We strongly recommend you validate your approach locally using methodology and reasoning, not by submitting many variations.

9. Sample submission
A sample submission CSV that matches this spec is included in your hackathon bundle as sample_submission.csv. It is not a high-quality ranking — it's only a format reference.

10. What you submit (full picture)
Your submission consists of three parts, all required:
10.1 The CSV file
The top-100 ranking, as specified in Sections 2 and 3.
10.2 Portal metadata
Collected at upload time via the submission form. Have these ready before you start the upload:

10.3 Code repository
Your GitHub repo should include:
A clear README.md with setup instructions and exact commands to reproduce your submission CSV
The full source code that produced the CSV (no hidden steps, no manual edits)
Any pre-computed artifacts your code depends on (embeddings, indexes, model weights), or a script that produces them
A requirements.txt, pyproject.toml, or equivalent specifying all dependencies and versions
A submission_metadata.yaml at the repo root mirroring your portal metadata (use the template provided in the hackathon bundle as submission_metadata_template.yaml)
For Stage 3 code reproduction, your README must indicate a single command that produces the submission CSV from the candidates file. For example:
python rank.py --candidates ./candidates.jsonl --out ./submission.csv
If your system requires pre-computation (e.g., generating embeddings), document this clearly — pre-computation may exceed the 5-minute window, but the ranking step that produces the CSV must complete within it.
10.4 AI tools declaration — what it means
The hackathon permits AI tool use. We've designed the evaluation pipeline so that AI-assisted submissions where the human did real engineering work will succeed, while AI-only submissions (paste-and-pray) will fail at Stage 3 (compute reproduction), Stage 4 (no real code repo), or Stage 5 (cannot defend the work).
The declaration is for transparency, not filtering. Be honest. If your interview answers contradict your declaration, that's a much stronger negative signal than the AI use itself.
10.5 Sandbox / demo link requirement
A sandbox is a hosted environment where organizers (and you) can verify your ranking system runs reproducibly. Acceptable sandbox platforms include:
HuggingFace Spaces (free tier is fine)
Streamlit Cloud (free tier is fine)
Replit (public repl)
Google Colab (with link to a notebook that runs end-to-end)
A docker pull + docker run link to a public registry image
A binder link for a runnable Jupyter notebook
Your sandbox needs to:
Accept a small candidate sample (≤100 candidates) as input — either via upload or pre-loaded
Run your ranking system end-to-end and produce a ranked CSV
Complete within the compute budget (≤5 min on CPU)
It does not need to handle the full 100K pool — small-sample reproducibility is what we're checking. The full reproduction at Stage 3 happens in our own sandbox.
Why it's mandatory: at Stage 3 we will reproduce your full ranking step from your GitHub repo. The sandbox is a faster, lower-stakes sanity check that lets us (and you) verify the code runs at all before we invest in full reproduction. Submissions without a working sandbox link are flagged at Stage 1.
If you have a strong reason a hosted sandbox is impractical for your approach, you can submit a self-contained docker run recipe in your GitHub README instead — but the dockerfile must build and run unmodified.

In [42]:
top100 = ranked.head(100).copy()

print(top100.head())
print(len(top100))

       candidate_id    score  rank
86021  CAND_0086022  0.84740     1
11686  CAND_0011687  0.82360     2
45861  CAND_0045862  0.79745     3
37565  CAND_0037566  0.78075     4
29366  CAND_0029367  0.77950     5
100

In [43]:
def generate_reason(c):

    skills = [s["name"] for s in c["skills"]]

    ai_skills = [
        x for x in skills
        if x in AI_SKILLS
    ]

    exp = c["profile"]["years_of_experience"]

    return (
        f"{exp:.1f} years experience with "
        f"{', '.join(ai_skills[:5])}. "
        f"Strong behavioral signals and relevant AI/ML background."
    )

In [44]:
from docx import Document

path = "challenge_files/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_spec.docx"

doc = Document(path)

for para in doc.paragraphs:
    print(para.text)

Submission Specification — Redrob Hackathon v4
Read this carefully before submitting. Submissions that don't match this spec will be auto-rejected by the validator without scoring.

1. What you're submitting
A CSV file ranking the top 100 candidates from candidates.jsonl for the released job description.
Rank 1 is the best fit; rank 100 is the 100th best fit.
You do not rank candidates 101 onward — only the top 100.

2. File format
Filename
Your team's registered participant ID, with .csv extension. For example: team_xxx.csv.
Encoding
UTF-8.
Required columns (in this order)
candidate_id,rank,score,reasoning

Example
candidate_id,rank,score,reasoning
CAND_0042871,1,0.987,"Senior AI Engineer with 7 years building RAG systems at product companies; strong recent engagement and Bangalore-based."
CAND_0019884,2,0.973,"6 years applied ML; previously shipped vector search at scale; matches the 'product over research' profile in the JD."
CAND_0091235,3,0.962,"Strong NLP + retrieval background; some concern on notice period (120 days) but otherwise strong fit."
...
CAND_0007729,100,0.412,"Adjacent skills only — likely below cutoff but included as final filler given experience and engagement signals."

3. Rules
Format
Exactly 100 rows of data (plus 1 header row).
Each rank (1 through 100) appears exactly once.
Each candidate_id appears exactly once.
Every candidate_id must exist in the released candidates.jsonl.
score is non-increasing with rank — i.e., score at rank 1 ≥ score at rank 2 ≥ ... ≥ score at rank 100. Ties are allowed.
If two candidates have the same score, you must still assign unique ranks. Break score ties deterministically using a secondary signal from your model, or by candidate_id ascending.
Compute constraints
Your code that produces the submission must satisfy the following constraints:

Why these constraints? This is a real-world recruiting system, not a benchmark. A system that calls GPT-4 or Claude per candidate cannot scale to a 200K candidate pool in production. We want systems that have thought about latency-quality tradeoffs.
In practice, running an LLM call for each of 100,000 candidates will not fit the 5-minute CPU budget, even if the model runs locally. Plan for a small ranker over precomputed features, indexes, or compact local models.
You CANNOT, during the ranking step:
Call hosted LLM APIs.
Use GPUs.
Exceed the runtime/memory limits.
Enforcement. At Stage 3, top-N submissions must provide their full code repository. Your ranking step will be reproduced inside a sandboxed Docker container matching these constraints exactly. If your submission cannot be reproduced within these limits, it is disqualified at Stage 3, regardless of your composite score. Make sure your code runs locally on a 16 GB CPU-only machine within 5 minutes before you submit.
Three-submission cap
You may make at most 3 submissions total during the competition window. Your final entry is your last valid submission. Earlier submissions are not preserved.
We've kept this number low intentionally — without a live leaderboard, multiple submissions have limited value, and a low cap reduces gaming.
Reasoning column
The reasoning column is optional but heavily recommended. Top N submissions are advanced to Stage 4 (manual review) where reasoning quality is part of the evaluation.
At Stage 4, we sample 10 random rows from your submission and check each reasoning entry against the following:

What's penalized:
Empty reasoning
All-identical reasoning strings
Templated reasoning that just inserts the candidate's name
Reasoning that mentions skills not in the candidate's profile (hallucination)
Reasoning that contradicts the rank
Plain-language reasoning that demonstrates you actually understood the candidate's profile will rank highly here. Don't try to be impressive; try to be specific and honest.

4. How submissions are scored
Metrics
Your top-100 ranking is scored against the hidden ground truth using these metrics:

Final composite
Final composite = 0.50 × NDCG@10 + 0.30 × NDCG@50 + 0.15 × MAP + 0.05 × P@10
Scoring happens once, after submissions close. There is no public partition, no live leaderboard, and no per-submission feedback during the competition. Your score is computed against the full hidden ground truth and is revealed only when final results are announced.
Tiebreaks
If two submissions have identical composites:
Higher P@5 wins.
Higher P@10 wins.
Earlier submission timestamp wins.

5. Evaluation pipeline (stages)
Your submission flows through these stages:

Note on AI tool usage: You are allowed to use AI tools (Claude, GPT-4, etc.) as part of your development workflow. We expect many participants will. The evaluation is designed so that AI-assisted submissions where the human did real engineering work will succeed, while submissions that are mostly LLM output with minimal human engineering will fail at Stages 3-5. The compute constraint, code repo check, and defend-your-work interview together filter for genuine engineering, not for absence of AI use.

6. Common rejections (we see these every hackathon)
99 rows or 101 rows instead of exactly 100.
Ranks starting at 0 instead of 1.
Duplicate candidate_ids.
candidate_id typos that don't exist in candidates.jsonl.
All scores set to the same value (model isn't differentiating).
Scores increasing as rank increases (rank 1 has lowest score).
Submission file submitted as .xlsx or .json instead of .csv.
Double-check these locally before uploading — the server-side auto-validator rejects on any of them.

7. Honeypot warning
The dataset contains a small number (~80) of honeypot candidates with subtly impossible profiles (e.g., 8 years of experience at a company founded 3 years ago; "expert" proficiency in 10 skills with 0 years used). These are forced to relevance tier 0 in the ground truth.
If your submission ranks honeypots in the top 10, this is a strong signal that your system isn't reading profiles — it's just doing keyword embedding. We use the honeypot rate as a Stage 3 filter: submissions with honeypot rate > 10% in top 100 are disqualified.
You can identify honeypots through careful profile inspection. We expect a good ranking system to naturally avoid them; you don't need to special-case them.

8. Leaderboard policy
The leaderboard is hidden during the competition. You will not see your score until final results are announced. We strongly recommend you validate your approach locally using methodology and reasoning, not by submitting many variations.

9. Sample submission
A sample submission CSV that matches this spec is included in your hackathon bundle as sample_submission.csv. It is not a high-quality ranking — it's only a format reference.

10. What you submit (full picture)
Your submission consists of three parts, all required:
10.1 The CSV file
The top-100 ranking, as specified in Sections 2 and 3.
10.2 Portal metadata
Collected at upload time via the submission form. Have these ready before you start the upload:

10.3 Code repository
Your GitHub repo should include:
A clear README.md with setup instructions and exact commands to reproduce your submission CSV
The full source code that produced the CSV (no hidden steps, no manual edits)
Any pre-computed artifacts your code depends on (embeddings, indexes, model weights), or a script that produces them
A requirements.txt, pyproject.toml, or equivalent specifying all dependencies and versions
A submission_metadata.yaml at the repo root mirroring your portal metadata (use the template provided in the hackathon bundle as submission_metadata_template.yaml)
For Stage 3 code reproduction, your README must indicate a single command that produces the submission CSV from the candidates file. For example:
python rank.py --candidates ./candidates.jsonl --out ./submission.csv
If your system requires pre-computation (e.g., generating embeddings), document this clearly — pre-computation may exceed the 5-minute window, but the ranking step that produces the CSV must complete within it.
10.4 AI tools declaration — what it means
The hackathon permits AI tool use. We've designed the evaluation pipeline so that AI-assisted submissions where the human did real engineering work will succeed, while AI-only submissions (paste-and-pray) will fail at Stage 3 (compute reproduction), Stage 4 (no real code repo), or Stage 5 (cannot defend the work).
The declaration is for transparency, not filtering. Be honest. If your interview answers contradict your declaration, that's a much stronger negative signal than the AI use itself.
10.5 Sandbox / demo link requirement
A sandbox is a hosted environment where organizers (and you) can verify your ranking system runs reproducibly. Acceptable sandbox platforms include:
HuggingFace Spaces (free tier is fine)
Streamlit Cloud (free tier is fine)
Replit (public repl)
Google Colab (with link to a notebook that runs end-to-end)
A docker pull + docker run link to a public registry image
A binder link for a runnable Jupyter notebook
Your sandbox needs to:
Accept a small candidate sample (≤100 candidates) as input — either via upload or pre-loaded
Run your ranking system end-to-end and produce a ranked CSV
Complete within the compute budget (≤5 min on CPU)
It does not need to handle the full 100K pool — small-sample reproducibility is what we're checking. The full reproduction at Stage 3 happens in our own sandbox.
Why it's mandatory: at Stage 3 we will reproduce your full ranking step from your GitHub repo. The sandbox is a faster, lower-stakes sanity check that lets us (and you) verify the code runs at all before we invest in full reproduction. Submissions without a working sandbox link are flagged at Stage 1.
If you have a strong reason a hosted sandbox is impractical for your approach, you can submit a self-contained docker run recipe in your GitHub README instead — but the dockerfile must build and run unmodified.

In [45]:
top100 = ranked.head(100).copy()

print(len(top100))

100

In [46]:
AI_SKILLS = {
    "NLP","Fine-tuning LLMs","LoRA","Milvus",
    "BentoML","Feature Engineering",
    "PyTorch","TensorFlow","Transformers"
}

candidate_lookup = {
    c["candidate_id"]: c
    for c in candidates
}

def create_reason(candidate):

    exp = candidate["profile"].get(
        "years_of_experience", 0
    )

    skills = [
        s["name"]
        for s in candidate["skills"]
    ]

    matched = [
        s for s in skills
        if s in AI_SKILLS
    ]

    signals = candidate["redrob_signals"]

    return (
        f"{exp:.1f} years experience. "
        f"Relevant skills: {', '.join(matched[:4]) if matched else 'AI/ML exposure'}. "
        f"Recruiter response rate {signals.get('recruiter_response_rate',0):.2f} "
        f"and interview completion rate {signals.get('interview_completion_rate',0):.2f}."
    )

In [47]:
reasons = []

for cid in top100["candidate_id"]:

    candidate = candidate_lookup[cid]

    reasons.append(
        create_reason(candidate)
    )

top100["reasoning"] = reasons

In [48]:
submission = top100[
    [
        "candidate_id",
        "rank",
        "score",
        "reasoning"
    ]
]

In [49]:
print(submission.head())

print(submission.columns.tolist())

print(submission.shape)

       candidate_id  rank    score  \
86021  CAND_0086022     1  0.84740
11686  CAND_0011687     2  0.82360
45861  CAND_0045862     3  0.79745
37565  CAND_0037566     4  0.78075
29366  CAND_0029367     5  0.77950

                                               reasoning
86021  5.3 years experience. Relevant skills: Fine-tu...
11686  7.8 years experience. Relevant skills: TensorF...
45861  6.7 years experience. Relevant skills: NLP, Fe...
37565  6.9 years experience. Relevant skills: NLP, Lo...
29366  5.7 years experience. Relevant skills: BentoML...
['candidate_id', 'rank', 'score', 'reasoning']
(100, 4)

In [50]:
submission.to_csv(
    "YOUR_TEAM_ID.csv",
    index=False
)

In [51]:
submission.head(20)

,candidate_id,rank,score,reasoning
86021,CAND_0086022,1,0.84740,5.3 years experience. Relevant skills: Fine-tu...
11686,CAND_0011687,2,0.82360,7.8 years experience. Relevant skills: TensorF...
45861,CAND_0045862,3,0.79745,"6.7 years experience. Relevant skills: NLP, Fe..."
37565,CAND_0037566,4,0.78075,"6.9 years experience. Relevant skills: NLP, Lo..."
29366,CAND_0029367,5,0.77950,5.7 years experience. Relevant skills: BentoML...
77284,CAND_0077285,6,0.76490,"5.5 years experience. Relevant skills: LoRA, F..."
37979,CAND_0037980,7,0.76180,"9.0 years experience. Relevant skills: LoRA, P..."
18498,CAND_0018499,8,0.76065,7.2 years experience. Relevant skills: Milvus....
60071,CAND_0060072,9,0.76010,5.7 years experience. Relevant skills: PyTorch...
2024,CAND_0002025,10,0.75635,5.9 years experience. Relevant skills: TensorF...
41609,CAND_0041610,11,0.75400,"6.7 years experience. Relevant skills: LoRA, F..."
88024,CAND_0088025,12,0.75195,8.6 years experience. Relevant skills: TensorF...
77955,CAND_0077956,13,0.75085,"6.4 years experience. Relevant skills: Milvus,..."
70397,CAND_0070398,14,0.74945,7.2 years experience. Relevant skills: PyTorch...
49537,CAND_0049538,15,0.74610,5.8 years experience. Relevant skills: Feature...
74338,CAND_0074339,16,0.74545,5.3 years experience. Relevant skills: PyTorch...
86150,CAND_0086151,17,0.74420,7.7 years experience. Relevant skills: BentoML...
1929,CAND_0001930,18,0.74380,"6.9 years experience. Relevant skills: NLP, Be..."
73313,CAND_0073314,19,0.74185,5.2 years experience. Relevant skills: BentoML...
33384,CAND_0033385,20,0.74015,6.0 years experience. Relevant skills: Feature...

In [52]:
print(submission.shape)
print(submission["rank"].min(), submission["rank"].max())
print(submission["candidate_id"].nunique())

(100, 4)
1 100
100

In [53]:
submission.to_csv(
    "YOUR_TEAM_ID.csv",
    index=False
)

In [54]:
from google.colab import files
files.download("YOUR_TEAM_ID.csv")

In [55]:
for cid in submission.head(10)["candidate_id"]:
    c = candidate_lookup[cid]
    print("="*80)
    print(cid)
    print(c["profile"]["headline"])
    print(c["profile"]["summary"][:500])

================================================================================
CAND_0086022
Senior Applied Scientist | LLMs, RAG, Vector Search | ex-Top Tech
Senior AI engineer with 5.3 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I led the migration from keyword-based ranking to a learning-to-rank model with embedded behavioral signals, handling peak QPS of 8K with sub-200ms p95. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it
================================================================================
CAND_0011687
Senior NLP Engineer | Production ML at scale | 7.8+ yrs
Senior AI engineer with 7.8 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I owned the offline-online evaluation harness — NDCG/MRR/recall calibrated to live A/B metrics, with an index footprint of ~600GB and incremental refresh every 15 min. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluatio
================================================================================
CAND_0045862
AI Specialist | Data Science & ML enthusiast
Data scientist / ML engineer with 6.7 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. Most of my recent work has been on predictive modeling for customer-facing problems — churn, conversion, lifetime value. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML
================================================================================
CAND_0037566
Machine Learning Engineer | Search, Ranking & Retrieval
Machine learning engineer with 6.9 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I shipped our first RAG-based feature this year and now own the eval framework for it. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shi
================================================================================
CAND_0029367
Senior Data Scientist | Applied ML | Building intelligent products
Machine learning engineer with 5.7 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I've been the de-facto ML lead on a small team, shipping models across NLP and recsys. I've spent enough time debugging production ranking issues to know which signals matter and which are noise. My academic background is in CS/ML but my main learn
================================================================================
CAND_0077285
Recommendation Systems Engineer | ML, NLP, Recommendation Systems
Machine learning engineer with 5.5 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, my main project for the last 18 months has been the recommendation system that powers our discovery feed. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background
================================================================================
CAND_0037980
Senior Engineer | Information Retrieval at scale
Senior engineer who has spent the last several years building systems that connect users with relevant information at scale. Comfortable across the full stack from infrastructure to algorithms to product experience, though most of my time has been in the middle layer — the ranking and retrieval systems that decide what to show. Strong preference for shipping real systems over research-only work; I'd rather have a working v1 in 6 weeks than a perfect v2 in 6 months. I've made the standard mistake
================================================================================
CAND_0018499
Senior Machine Learning Engineer | Building AI-native search & ranking systems
Senior AI engineer with 7.2 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I designed the company's first hybrid retrieval system combining BM25 with dense vector recall, serving 50M+ queries per month. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it all together. I've shippe
================================================================================
CAND_0060072
Staff Machine Learning Engineer | LLMs, RAG, Vector Search | ex-Top Tech
Senior AI engineer with 5.7 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I led the migration from keyword-based ranking to a learning-to-rank model with embedded behavioral signals, handling peak QPS of 8K with sub-200ms p95. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it
================================================================================
CAND_0002025
Senior AI Engineer | Building AI-native search & ranking systems
Senior AI engineer with 5.9 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I designed the company's first hybrid retrieval system combining BM25 with dense vector recall, across a corpus of 30M+ candidate profiles. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it all together.

In [56]:
for cid in submission.head(20)["candidate_id"]:
    c = candidate_lookup[cid]

    s = c["redrob_signals"]

    print(
        cid,
        "response:", s.get("recruiter_response_rate"),
        "interview:", s.get("interview_completion_rate"),
        "offer:", s.get("offer_acceptance_rate"),
        "github:", s.get("github_activity_score"),
        "notice:", s.get("notice_period_days")
    )

CAND_0086022 response: 0.55 interview: 0.68 offer: 0.53 github: 75.2 notice: 0
CAND_0011687 response: 0.89 interview: 0.77 offer: 0.6 github: 76.3 notice: 15
CAND_0045862 response: 0.54 interview: 0.71 offer: 0.68 github: 58.9 notice: 90
CAND_0037566 response: 0.5 interview: 0.84 offer: 0.67 github: 73.4 notice: 15
CAND_0029367 response: 0.77 interview: 0.58 offer: 0.39 github: 39.8 notice: 90
CAND_0077285 response: 0.56 interview: 0.67 offer: -1 github: 75.6 notice: 60
CAND_0037980 response: 0.63 interview: 0.89 offer: 0.83 github: 30.8 notice: 0
CAND_0018499 response: 0.61 interview: 0.8 offer: 0.75 github: 94.8 notice: 15
CAND_0060072 response: 0.1 interview: 0.99 offer: 0.46 github: 82.4 notice: 90
CAND_0002025 response: 0.8 interview: 0.81 offer: 0.46 github: 96.9 notice: 30
CAND_0041610 response: 0.52 interview: 0.8 offer: 0.8 github: 52.1 notice: 30
CAND_0088025 response: 0.83 interview: 0.95 offer: 0.82 github: 74.6 notice: 90
CAND_0077956 response: 0.88 interview: 1.0 offer: 0.62 github: 40.7 notice: 120
CAND_0070398 response: 0.6 interview: 0.64 offer: 0.63 github: 63.1 notice: 120
CAND_0049538 response: 0.72 interview: 0.67 offer: 0.59 github: 90.8 notice: 30
CAND_0074339 response: 0.58 interview: 0.81 offer: -1 github: 18.9 notice: 120
CAND_0086151 response: 0.52 interview: 0.6 offer: 0.35 github: 51.7 notice: 120
CAND_0001930 response: 0.65 interview: 0.95 offer: 0.66 github: 76.3 notice: 120
CAND_0073314 response: 0.84 interview: 0.55 offer: 0.67 github: 67.0 notice: 60
CAND_0033385 response: 0.65 interview: 0.77 offer: 0.58 github: -1 notice: 120

In [57]:
for cid in submission.head(20)["candidate_id"]:
    c = candidate_lookup[cid]

    print("="*80)
    print(cid)

    print(
        "Experience:",
        c["profile"]["years_of_experience"]
    )

    for skill in c["skills"][:10]:
        print(
            skill["name"],
            skill["duration_months"]
        )

================================================================================
CAND_0086022
Experience: 5.3
Vector Search 36
MLflow 46
Recommendation Systems 53
Databricks 15
Deep Learning 28
pgvector 78
Fine-tuning LLMs 69
Elasticsearch 35
QLoRA 54
Pinecone 63
================================================================================
CAND_0011687
Experience: 7.8
TensorFlow 56
OpenSearch 92
FAISS 42
PEFT 75
Feature Engineering 21
Embeddings 56
LangChain 63
MLOps 45
Weaviate 60
PyTorch 39
================================================================================
CAND_0045862
Experience: 6.7
NLP 27
Feature Engineering 31
MLflow 20
Haystack 55
Computer Vision 50
Recommendation Systems 46
BentoML 20
Fine-tuning LLMs 26
LlamaIndex 29
Illustrator 17
================================================================================
CAND_0037566
Experience: 6.9
Pinecone 74
Time Series 49
LlamaIndex 59
NLP 35
LoRA 58
QLoRA 61
BM25 19
Feature Engineering 29
Forecasting 47
MLflow 42
================================================================================
CAND_0029367
Experience: 5.7
GANs 49
Haystack 60
BentoML 12
MLflow 20
TensorFlow 60
QLoRA 49
FAISS 90
Sentence Transformers 95
RAG 89
NLP 83
================================================================================
CAND_0077285
Experience: 5.5
OpenCV 30
Excel 18
LoRA 79
Reinforcement Learning 19
Pinecone 51
Sentence Transformers 66
CNN 51
Embeddings 46
Information Retrieval 58
Fine-tuning LLMs 87
================================================================================
CAND_0037980
Experience: 9.0
LoRA 75
Search Infrastructure 48
PyTorch 63
NLP 54
Indexing Algorithms 58
BM25 92
TTS 48
Text Encoders 36
Document Processing 61
OpenCV 48
================================================================================
CAND_0018499
Experience: 7.2
Deep Learning 53
Weaviate 88
Recommendation Systems 46
scikit-learn 93
Diffusion Models 60
Pinecone 54
Information Retrieval 27
Milvus 40
QLoRA 43
RAG 94
================================================================================
CAND_0060072
Experience: 5.7
Deep Learning 49
Sentence Transformers 60
PyTorch 51
Feature Engineering 36
Milvus 26
Fine-tuning LLMs 40
Next.js 15
BM25 70
Redux 17
Qdrant 46
================================================================================
CAND_0002025
Experience: 5.9
Diffusion Models 31
FAISS 86
TensorFlow 85
scikit-learn 55
OpenSearch 50
Haystack 64
Weaviate 37
Sentence Transformers 81
QLoRA 81
NLP 38
================================================================================
CAND_0041610
Experience: 6.7
OpenCV 37
LoRA 32
Statistical Modeling 47
Data Science 33
Elasticsearch 94
GANs 34
OpenSearch 82
LangChain 20
BM25 75
scikit-learn 85
================================================================================
CAND_0088025
Experience: 8.6
Pinecone 49
QLoRA 83
LLMs 71
Hugging Face Transformers 55
RAG 41
SAP 7
TensorFlow 86
LoRA 22
Flask 14
Prompt Engineering 35
================================================================================
CAND_0077956
Experience: 6.4
Milvus 32
TTS 24
SQL 24
Weights & Biases 53
Hugging Face Transformers 33
Weaviate 59
LlamaIndex 35
BentoML 30
Flask 9
Feature Engineering 8
================================================================================
CAND_0070398
Experience: 7.2
Image Classification 27
Data Science 48
BM25 71
RAG 72
FAISS 90
Object Detection 36
Embeddings 92
PyTorch 55
LoRA 41
Python 40
================================================================================
CAND_0049538
Experience: 5.8
LlamaIndex 41
Feature Engineering 45
MLflow 35
Computer Vision 19
TTS 44
Learning to Rank 47
OpenSearch 64
Vector Search 41
Milvus 91
QLoRA 53
================================================================================
CAND_0074339
Experience: 5.3
Salesforce CRM 16
OpenCV 31
PyTorch 18
Marketing 5
OpenSearch 39
Learning to Rank 23
Tailwind 9
FAISS 31
Time Series 55
Image Classification 56
================================================================================
CAND_0086151
Experience: 7.7
Figma 26
LangChain 43
BentoML 8
Data Science 28
Snowflake 15
Recommendation Systems 44
Qdrant 73
OpenSearch 48
Embeddings 38
PEFT 49
================================================================================
CAND_0001930
Experience: 6.9
Machine Learning 34
GraphQL 27
Webpack 9
CSS 9
Kubeflow 33
NLP 19
Embeddings 24
Statistical Modeling 27
BentoML 30
Milvus 46
================================================================================
CAND_0073314
Experience: 5.2
BentoML 19
Prompt Engineering 26
Feature Engineering 44
Weights & Biases 24
Image Classification 14
PEFT 53
Milvus 16
Elasticsearch 8
MLflow 21
PyTorch 14
================================================================================
CAND_0033385
Experience: 6.0
Scrum 6
GCP 25
Feature Engineering 29
CSS 16
Kafka 2
Salesforce CRM 9
Kubernetes 8
Embeddings 18
Fine-tuning LLMs 15
Sentence Transformers 13

In [58]:
offer = max(
    0,
    signals.get(
        "offer_acceptance_rate",
        0
    )
)

github = max(
    0,
    signals.get(
        "github_activity_score",
        0
    )
)

NameError: name 'signals' is not defined

In [59]:
def behavior_score(c):

    signals = c["redrob_signals"]

    recruiter_response = max(
        0,
        signals.get(
            "recruiter_response_rate",
            0
        )
    )

    interview_completion = max(
        0,
        signals.get(
            "interview_completion_rate",
            0
        )
    )

    offer_acceptance = max(
        0,
        signals.get(
            "offer_acceptance_rate",
            0
        )
    )

    github_activity = max(
        0,
        signals.get(
            "github_activity_score",
            0
        )
    ) / 100

    profile_completeness = min(
        signals.get(
            "profile_completeness_score",
            0
        ) / 100,
        1
    )

    open_to_work = (
        1
        if signals.get(
            "open_to_work_flag",
            False
        )
        else 0
    )

    score = (
        0.20 * recruiter_response
        + 0.20 * interview_completion
        + 0.10 * offer_acceptance
        + 0.20 * github_activity
        + 0.20 * profile_completeness
        + 0.10 * open_to_work
    )

    return score

In [60]:
scores = []

for c in candidates:
    scores.append({
        "candidate_id": c["candidate_id"],
        "score": final_score(c)
    })

In [61]:
ranked = pd.DataFrame(scores)

ranked = ranked.sort_values(
    "score",
    ascending=False
)

ranked["rank"] = range(
    1,
    len(ranked)+1
)

In [62]:
top100 = ranked.head(100).copy()

In [63]:
for cid in ranked.head(10)["candidate_id"]:

    c = candidate_lookup[cid]

    print("="*80)
    print(cid)
    print(c["profile"]["headline"])
    print(c["profile"]["summary"][:500])

================================================================================
CAND_0086022
Senior Applied Scientist | LLMs, RAG, Vector Search | ex-Top Tech
Senior AI engineer with 5.3 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I led the migration from keyword-based ranking to a learning-to-rank model with embedded behavioral signals, handling peak QPS of 8K with sub-200ms p95. My day-to-day work spans embedding model selection and fine-tuning, hybrid retrieval architecture, learning-to-rank, behavioral-signal integration, and the offline/online evaluation that ties it
================================================================================
CAND_0037980
Senior Engineer | Information Retrieval at scale
Senior engineer who has spent the last several years building systems that connect users with relevant information at scale. Comfortable across the full stack from infrastructure to algorithms to product experience, though most of my time has been in the middle layer — the ranking and retrieval systems that decide what to show. Strong preference for shipping real systems over research-only work; I'd rather have a working v1 in 6 weeks than a perfect v2 in 6 months. I've made the standard mistake
================================================================================
CAND_0045862
AI Specialist | Data Science & ML enthusiast
Data scientist / ML engineer with 6.7 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. Most of my recent work has been on predictive modeling for customer-facing problems — churn, conversion, lifetime value. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML
================================================================================
CAND_0077956
Computer Vision Engineer | 6.4 yrs in analytics & ML
Data scientist / ML engineer with 6.4 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. I want to g
================================================================================
CAND_0077285
Recommendation Systems Engineer | ML, NLP, Recommendation Systems
Machine learning engineer with 5.5 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, my main project for the last 18 months has been the recommendation system that powers our discovery feed. Along the way I've gotten comfortable with the operational side — A/B testing, drift monitoring, retraining schedules. My academic background
================================================================================
CAND_0001930
Senior Software Engineer (ML) | 6.9 yrs in analytics & ML
Data scientist / ML engineer with 6.9 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. I want to grow into senior A
================================================================================
CAND_0073314
Senior Software Engineer (ML) | Building ML-powered solutions
Data scientist / ML engineer with 5.2 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. Most of my recent work has been on predictive modeling for customer-facing problems — churn, conversion, lifetime value. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML
================================================================================
CAND_0037566
Machine Learning Engineer | Search, Ranking & Retrieval
Machine learning engineer with 6.9 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I shipped our first RAG-based feature this year and now own the eval framework for it. I've learned that most retrieval problems are actually evaluation problems in disguise. My academic background is in CS/ML but my main learning has come from shi
================================================================================
CAND_0007567
AI Specialist | 6.1 yrs in analytics & ML
Data scientist / ML engineer with 6.1 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like collaborative filtering and gradient-boosted models. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building dep
================================================================================
CAND_0050454
AI Engineer | Applied ML | Building intelligent products
Machine learning engineer with 6.8 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-based product to embedding-based retrieval. I care a lot about evaluation rigor — too many teams ship models without offline benchmarks they trust. My academic background is in CS/ML but my main learn

In [64]:
ranked.head(20)

       candidate_id    score  rank
86021  CAND_0086022  0.72740     1
37979  CAND_0037980  0.72180     2
45861  CAND_0045862  0.71745     3
77955  CAND_0077956  0.71085     4
77284  CAND_0077285  0.70990     5
1929   CAND_0001930  0.70380     6
73313  CAND_0073314  0.70185     7
37565  CAND_0037566  0.70075     8
7566   CAND_0007567  0.69820     9
50453  CAND_0050454  0.68835    10
14439  CAND_0014440  0.68815    11
29438  CAND_0029439  0.68420    12
5310   CAND_0005311  0.68285    13
39382  CAND_0039383  0.68120    14
15492  CAND_0015493  0.67655    15
2024   CAND_0002025  0.67635    16
88024  CAND_0088025  0.67195    17
46352  CAND_0046353  0.67030    18
83851  CAND_0083852  0.66990    19
5537   CAND_0005538  0.66685    20

In [65]:
for cid in ["CAND_0074339", "CAND_0033385"]:

    row = ranked[
        ranked["candidate_id"] == cid
    ]

    print(row)

       candidate_id    score  rank
74338  CAND_0074339  0.65045    37
       candidate_id    score  rank
33384  CAND_0033385  0.58065   385

In [66]:
print(submission.shape)
print(submission.head())
print(submission.tail())

(100, 4)
       candidate_id  rank    score  \
86021  CAND_0086022     1  0.84740
11686  CAND_0011687     2  0.82360
45861  CAND_0045862     3  0.79745
37565  CAND_0037566     4  0.78075
29366  CAND_0029367     5  0.77950

                                               reasoning
86021  5.3 years experience. Relevant skills: Fine-tu...
11686  7.8 years experience. Relevant skills: TensorF...
45861  6.7 years experience. Relevant skills: NLP, Fe...
37565  6.9 years experience. Relevant skills: NLP, Lo...
29366  5.7 years experience. Relevant skills: BentoML...
       candidate_id  rank    score  \
11161  CAND_0011162    96  0.67995
78668  CAND_0078669    97  0.67905
91551  CAND_0091552    98  0.67865
83789  CAND_0083790    99  0.67850
76318  CAND_0076319   100  0.67840

                                               reasoning
11161  5.8 years experience. Relevant skills: LoRA, M...
78668  6.3 years experience. Relevant skills: Feature...
91551  7.8 years experience. Relevant skills: BentoML...
83789  3.5 years experience. Relevant skills: LoRA, N...
76318  8.5 years experience. Relevant skills: BentoML...

In [67]:
top100 = ranked.head(100).copy()

reasons = []

for cid in top100["candidate_id"]:
    candidate = candidate_lookup[cid]
    reasons.append(create_reason(candidate))

top100["reasoning"] = reasons

submission = top100[
    [
        "candidate_id",
        "rank",
        "score",
        "reasoning"
    ]
]

print(submission.head())
print(submission.shape)

       candidate_id  rank    score  \
86021  CAND_0086022     1  0.72740
37979  CAND_0037980     2  0.72180
45861  CAND_0045862     3  0.71745
77955  CAND_0077956     4  0.71085
77284  CAND_0077285     5  0.70990

                                               reasoning
86021  5.3 years experience. Relevant skills: Fine-tu...
37979  9.0 years experience. Relevant skills: LoRA, P...
45861  6.7 years experience. Relevant skills: NLP, Fe...
77955  6.4 years experience. Relevant skills: Milvus,...
77284  5.5 years experience. Relevant skills: LoRA, F...
(100, 4)

In [68]:
print(submission.shape)

print(
    submission["rank"].min(),
    submission["rank"].max()
)

print(
    submission["candidate_id"].nunique()
)

print(
    submission["score"].is_monotonic_decreasing
)

(100, 4)
1 100
100
True

In [69]:
submission.to_csv(
    "YOUR_TEAM_ID.csv",
    index=False
)

In [70]:
print(submission.shape)
print(submission.head())

(100, 4)
       candidate_id  rank    score  \
86021  CAND_0086022     1  0.72740
37979  CAND_0037980     2  0.72180
45861  CAND_0045862     3  0.71745
77955  CAND_0077956     4  0.71085
77284  CAND_0077285     5  0.70990

                                               reasoning
86021  5.3 years experience. Relevant skills: Fine-tu...
37979  9.0 years experience. Relevant skills: LoRA, P...
45861  6.7 years experience. Relevant skills: NLP, Fe...
77955  6.4 years experience. Relevant skills: Milvus,...
77284  5.5 years experience. Relevant skills: LoRA, F...

In [71]:
submission.to_csv(
    "YOUR_TEAM_ID.csv",
    index=False
)

In [72]:
from google.colab import files
files.download("YOUR_TEAM_ID.csv")